### PR TITLE
Fix for negative durations

### LINKED ISSUE #1174: SingularityDeployPoller IllegalArgumentException: durationMillis must not be negative
Singularity 0.6.2 crashed with:

```
DEBUG [2016-07-27 20:48:55,840] com.hubspot.singularity.scheduler.SingularityDeployChecker: Checking a deploy SingularityPendingDeploy [deployMarker=SingularityDeployMarker [requestId=mobile-web-frontend, deployId=teamcity.2016.07.27T20.48.55, timestamp=1469652535842, user=Optional.absent(), message=Optional.a
bsent()], lastLoadBalancerUpdate=Optional.absent(), currentDeployState=WAITING, deployProgress=Optional.of(SingularityIncrementalDeployProgress{targetActiveInstances=4, deployInstanceCountPerStep=4, deployStepWaitTimeMs=0, stepComplete=false, autoAdvanceDeploySteps=true, failedDeployTasks=[], timestamp=1469652
535842})]
ERROR [2016-07-27 20:48:55,841] com.hubspot.singularity.scheduler.SingularityLeaderOnlyPoller: Caught an exception while running SingularityDeployPoller
! java.lang.IllegalArgumentException: durationMillis must not be negative
! at org.apache.commons.lang3.Validate.inclusiveBetween(Validate.java:969) ~[singularity-0.6.2.jar:0.6.2]
! at org.apache.commons.lang3.time.DurationFormatUtils.formatDuration(DurationFormatUtils.java:131) ~[singularity-0.6.2.jar:0.6.2]
! at org.apache.commons.lang3.time.DurationFormatUtils.formatDuration(DurationFormatUtils.java:114) ~[singularity-0.6.2.jar:0.6.2]
! at org.apache.commons.lang3.time.DurationFormatUtils.formatDurationHMS(DurationFormatUtils.java:83) ~[singularity-0.6.2.jar:0.6.2]
! at com.hubspot.singularity.scheduler.SingularityDeployChecker.isDeployOverdue(SingularityDeployChecker.java:310) ~[singularity-0.6.2.jar:0.6.2]
! at com.hubspot.singularity.scheduler.SingularityDeployChecker.checkDeployProgress(SingularityDeployChecker.java:466) ~[singularity-0.6.2.jar:0.6.2]
! at com.hubspot.singularity.scheduler.SingularityDeployChecker.getDeployResult(SingularityDeployChecker.java:431) ~[singularity-0.6.2.jar:0.6.2]
! at com.hubspot.singularity.scheduler.SingularityDeployChecker.checkDeploy(SingularityDeployChecker.java:150) ~[singularity-0.6.2.jar:0.6.2]
! at com.hubspot.singularity.scheduler.SingularityDeployChecker.checkDeploys(SingularityDeployChecker.java:98) ~[singularity-0.6.2.jar:0.6.2]
! at com.hubspot.singularity.scheduler.SingularityDeployPoller.runActionOnPoll(SingularityDeployPoller.java:35) ~[singularity-0.6.2.jar:0.6.2]
! at com.hubspot.singularity.scheduler.SingularityLeaderOnlyPoller.runActionIfLeaderAndMesosIsRunning(SingularityLeaderOnlyPoller.java:108) [singularity-0.6.2.jar:0.6.2]
! at com.hubspot.singularity.scheduler.SingularityLeaderOnlyPoller.access$000(SingularityLeaderOnlyPoller.java:24) [singularity-0.6.2.jar:0.6.2]
! at com.hubspot.singularity.scheduler.SingularityLeaderOnlyPoller$1.run(SingularityLeaderOnlyPoller.java:83) [singularity-0.6.2.jar:0.6.2]
! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_72-internal]
! at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_72-internal]
! at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_72-internal]
! at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_72-internal]
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_72-internal]
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_72-internal]
! at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72-internal]
ERROR [2016-07-27 20:48:55,850] com.hubspot.singularity.SingularityAbort: Singularity on mesos2-prod-sc is aborting due to UNRECOVERABLE_ERROR
```

Recovered after a leader election with no apparent further problems.

### PR DESCRIPTION
**Pull request by ssalinas**
A few of these have been reported now. There is no reason Singularity should be crashing for this. Make sure the values are non-negative in these two cases.
/fixes #1174 #1251

### CODE REVIEW

File: SingularityService/src/main/java/com/hubspot/singularity/scheduler/SingularityDeployChecker.java [hunk 1]
```diff
@@ -149,7 +149,7 @@ private void checkDeploy(final SingularityPendingDeploy pendingDeploy, final Lis
     SingularityDeployResult deployResult =
       getDeployResult(request, cancelRequest, pendingDeploy, updatePendingDeployRequest, deployKey, deploy, deployMatchingTasks, allOtherMatchingTasks, inactiveDeployMatchingTasks);
 
-    LOG.info("Deploy {} had result {} after {}", pendingDeployMarker, deployResult, JavaUtils.durationFromMillis(System.currentTimeMillis() - pendingDeployMarker.getTimestamp()));
+    LOG.info("Deploy {} had result {} after {}", pendingDeployMarker, deployResult, JavaUtils.durationFromMillis(Math.max(System.currentTimeMillis() - pendingDeployMarker.getTimestamp(), 0)));
```
Comment (tpetr) [inline SingularityService/src/main/java/com/hubspot/singularity/scheduler/SingularityDeployChecker.java]: thoughts on moving `Math.max()` into `durationFromMillis()`?

Comment (ssalinas) [inline SingularityService/src/main/java/com/hubspot/singularity/scheduler/SingularityDeployChecker.java]: yeah that probably makes sense, I can move it

Comment (ssalinas) [inline SingularityService/src/main/java/com/hubspot/singularity/scheduler/SingularityDeployChecker.java]: updated
